/**
 * Wraps async calls in try catch blocks
 * to simplify syntax.
 *
 * source: https://github.com/scopsy/await-to-js/blob/master/src/await-to-js.ts
 */
export async function pTuple(promise) {
    return promise.then(data => [null, data]).catch(err => [err, undefined]);
}
